/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aritmatikahengki;

/**
 *
 * @author SMKIJO-HP02
 */
public class kalkulatorsederhana extends javax.swing.JFrame {

    /**
     * Creates new form kalkulatorsederhana
     */
    public kalkulatorsederhana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        input2 = new javax.swing.JTextField();
        input3 = new javax.swing.JTextField();
        penjumlahan = new javax.swing.JButton();
        pembagian = new javax.swing.JButton();
        pengurangan = new javax.swing.JButton();
        perkalian = new javax.swing.JButton();
        output = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 153));
        setBounds(new java.awt.Rectangle(2, 2, 2, 2));
        setFont(new java.awt.Font("Chiller", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(51, 0, 255));
        setSize(new java.awt.Dimension(2, 2));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("input1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 20));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("input2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("input3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("hasil");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, 30));

        input1.setBackground(new java.awt.Color(102, 255, 255));
        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        getContentPane().add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, -1));

        input2.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, -1));

        input3.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, -1));

        penjumlahan.setBackground(new java.awt.Color(51, 255, 255));
        penjumlahan.setForeground(new java.awt.Color(51, 51, 255));
        penjumlahan.setText("+");
        penjumlahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjumlahanActionPerformed(evt);
            }
        });
        getContentPane().add(penjumlahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 40, -1));

        pembagian.setBackground(new java.awt.Color(51, 255, 255));
        pembagian.setForeground(new java.awt.Color(0, 51, 255));
        pembagian.setText("/");
        pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianActionPerformed(evt);
            }
        });
        getContentPane().add(pembagian, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        pengurangan.setBackground(new java.awt.Color(51, 255, 255));
        pengurangan.setForeground(new java.awt.Color(0, 0, 204));
        pengurangan.setText("-");
        pengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penguranganActionPerformed(evt);
            }
        });
        getContentPane().add(pengurangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        perkalian.setBackground(new java.awt.Color(0, 255, 255));
        perkalian.setForeground(new java.awt.Color(51, 0, 255));
        perkalian.setText("x");
        perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkalianActionPerformed(evt);
            }
        });
        getContentPane().add(perkalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));
        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianActionPerformed
        int f1, f2, f3;
        double h;
        f1 = Integer.parseInt(input1.getText());
        f2 = Integer.parseInt(input2.getText());
        f3 = Integer.parseInt(input3.getText());
        h  = (f1 / f2 / f3);
        output.setText(String.valueOf(h)); 
    }//GEN-LAST:event_pembagianActionPerformed

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input1ActionPerformed

    private void penguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penguranganActionPerformed
        int f1, f2, f3, h;
        f1 = Integer.parseInt(input1.getText());
        f2 = Integer.parseInt(input2.getText());
        f3 = Integer.parseInt(input3.getText());
        h  = (f1 - f2 - f3);
        output.setText(String.valueOf(h)); 
    }//GEN-LAST:event_penguranganActionPerformed

    private void penjumlahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjumlahanActionPerformed
        int f1, f2, f3, h;
        f1 = Integer.parseInt(input1.getText());
        f2 = Integer.parseInt(input2.getText());
        f3 = Integer.parseInt(input3.getText());
        h  = (f1 + f2 + f3);
        output.setText(String.valueOf(h));        

    }//GEN-LAST:event_penjumlahanActionPerformed

    private void perkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkalianActionPerformed
        int f1, f2, f3, h;
        f1 = Integer.parseInt(input1.getText());
        f2 = Integer.parseInt(input2.getText());
        f3 = Integer.parseInt(input3.getText());
        h  = (f1 * f2 * f3);
        output.setText(String.valueOf(h)); 
    }//GEN-LAST:event_perkalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulatorsederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulatorsederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulatorsederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulatorsederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulatorsederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel output;
    private javax.swing.JButton pembagian;
    private javax.swing.JButton pengurangan;
    private javax.swing.JButton penjumlahan;
    private javax.swing.JButton perkalian;
    // End of variables declaration//GEN-END:variables
}
